name: Deploy pkgdown site

on:
  push:
    branches: [main]

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          install.packages("pkgdown")
        shell: Rscript {0}

      - name: Deploy site
        run: |
          pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
